inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml
require:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec
AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "db/migrate/*"
    - "db/seeds"
    - "config/initializers/*"
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Style/MethodCallWithArgsParentheses:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
Rspec/NamedSubject:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
